version: '3.8'

services:
  #Triton for Sigma Event Generator
  triton:
    container_name: sigma_gpu
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    ports:
      - 8090:8000  # HTTP API
      - 8091:8001  # gRPC API
      - 8092:8002  # Metrics
    volumes:
      - ./triton_model:/models:ro
    command: ["tritonserver", "--model-store=/models"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
  
  event-api:
    build: ./fastapi_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TRITON_HOST=triton:8001
    depends_on:
      - triton
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    user: "1000:1000"
